name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: astro build cache
        id: astro-build-cache
        uses: actions/cache@v3
        with:
          path: .cache
          key: ${{ runner.os }}-astro-build-${{ hashFiles('**/cache.json') }}

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: npm

      - name: install dependencies
        run: npm ci

      - name: check
        run: npm run check

      - name: build
        run: npm run build
