name: lint

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: npm

      - name: install dependencies
        run: npm ci

      - name: format
        run: npm run format-ci
      
      - name: lint
        run: npm run lint:eslint
